name: Test deploy                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - main                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Install dependencies    # 의존 파일 설치
        working-directory: ./frontend
        run: npm install
      
      - name: Generate build          # React Build
        working-directory: ./frontend
        run: npm run build

      - name : Set up JDK 17
        uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'
          
      - name : build      
        working-directory: ./backend
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with :
          arguments : build    
